title: Humayun Ahmed Ashik
description: A methodical Software QA Engineer with 5 years of experience in optimal testing strategies. Open and clear communicator with good multitasking skills, organized nature and strong attention to detail.
baseurl: "/resume/"
url: ""
photo_url: "my-photo.jpeg"

# This is an optional section
# You can skip filling in one or more of the items in this section
email: "humayunahmedashik@gmail.com"
linkedin: "https://www.linkedin.com/in/humayun-ashik/"
github: "https://github.com/humayun-ashik"
website: "https://humayun-ashik.github.io/"
medium: "https://humayun-ashik.medium.com/"

markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

exclude:
  - Gemfile
  - Gemfile.lock
  
